services:
  - type: web
    name: deepfake-detection
    env: python
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      pip install gdown tqdm requests
      mkdir -p model
      python download_models.py
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT --timeout 600 --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PORT
        value: 10000 